# Étape 1 : Construire l'application
FROM node:18-alpine AS builder

# Définir le répertoire de travail dans le conteneur
WORKDIR /app

# Copier les fichiers de configuration et installer les dépendances
COPY package.json package-lock.json ./
RUN npm install

# Copier tout le code source et construire l'application
COPY . .
RUN npm run build

# Étape 2 : Servir l'application avec Nginx
FROM nginx:alpine

# Copier les fichiers construits de l'étape précédente dans le dossier de Nginx
COPY --from=builder /app/dist /usr/share/nginx/html

# Copier la configuration de Nginx (optionnel)
# Si vous avez une configuration personnalisée de Nginx, décommentez cette ligne et assurez-vous d'avoir un fichier `nginx.conf` dans votre projet
# COPY nginx.conf /etc/nginx/nginx.conf

# Exposer le port 80 pour le service
EXPOSE 80

# Démarrer Nginx
CMD ["nginx", "-g", "daemon off;"]
