apiVersion: apps/v1
kind: Deployment
metadata:
  name: toto-liste
spec:
  replicas: 2
  selector:
    matchLabels:
      app: toto-liste
  template:
    metadata:
      labels:
        app: toto-liste
    spec:
      containers:
      - name: toto-liste
        image: votre_image_docker/toto-liste:latest
        ports:
        - containerPort: 80
